// === USER ACTION ===
export const USER_LOGIN_ACTION = 'USER_LOGIN_ACTION'
export const USER_LOGIN_SUCCESS_ACTION = 'USER_LOGIN_SUCCESS_ACTION'
export const USER_DETAIL_ACTION = 'USER_DETAIL_ACTION'
export const USER_UPDATE_ACTION = 'USER_UPDATE_ACTION'
export const LIST_STAFF_USER = 'LIST_STAFF_USER'

// STORE
export const LIST_STORE_ACTION = 'LIST_STORE_ACTION'
export const CREATE_STORE_ACTION = 'CREATE_STORE_ACTION'