// === USER ACTION ===
export const USER_LOGIN_ACTION = 'USER_LOGIN_ACTION'
export const USER_LOGIN_SUCCESS_ACTION = 'USER_LOGIN_SUCCESS_ACTION'
export const USER_DETAIL_ACTION = 'USER_DETAIL_ACTION'
export const USER_UPDATE_ACTION = 'USER_UPDATE_ACTION'